<template>
  <v-row justify="center" align="center">
    <v-col cols="12" sm="10" md="8" lg="6" xl="5">
      <DataTableComponent />
    </v-col>
  </v-row>
</template>

<script>
import DataTableComponent from '../components/DataTableComponent'
export default {
  name: 'IndexPage',
  components: {
    DataTableComponent,
  },
  data() {
    return {
      search: '',
      footerProps: {
        'items-per-page-options': [10, 25, 50, 75, { text: 'All', value: -1 }],
      },
      headers: [
        {
          text: 'Infinitive',
          align: 'start',
          value: 'infinitive',
        },
        { text: 'Translation', value: 'translation', sortable: false },
        { text: 'Past simple', value: 'pastSimple' },
        { text: 'Past participate', value: 'pastParticipate' },
      ],
      items: [
        {
          infinitive: 'be',
          translation: 'a fi',
          pastSimple: 'was/were',
          pastParticipate: 'been',
        },
        {
          infinitive: 'beat',
          translation: 'a bate',
          pastSimple: 'beat',
          pastParticipate: 'beaten',
        },
        {
          infinitive: 'become',
          translation: 'a deveni',
          pastSimple: 'became',
          pastParticipate: 'become',
        },
        {
          infinitive: 'begin',
          translation: 'a începe',
          pastSimple: 'began',
          pastParticipate: 'begun',
        },
        {
          infinitive: 'bend',
          translation: 'a îndoi',
          pastSimple: 'bent',
          pastParticipate: 'bent',
        },
        {
          infinitive: 'bite',
          translation: 'a mușca',
          pastSimple: 'bit',
          pastParticipate: 'bitten',
        },
        {
          infinitive: 'blow',
          translation: 'a sufla',
          pastSimple: 'blew',
          pastParticipate: 'blown',
        },
        {
          infinitive: 'break',
          translation: 'a rupe',
          pastSimple: 'broke',
          pastParticipate: 'broken',
        },
        {
          infinitive: 'bring',
          translation: 'a aduce',
          pastSimple: 'brought',
          pastParticipate: 'brought',
        },
        {
          infinitive: 'build',
          translation: 'a construi',
          pastSimple: 'built',
          pastParticipate: 'built',
        },
        {
          infinitive: 'burn',
          translation: 'a arde',
          pastSimple: 'burned/burnt',
          pastParticipate: 'burned/burnt',
        },
        {
          infinitive: 'burst',
          translation: 'a izbucni',
          pastSimple: 'burst',
          pastParticipate: 'burst',
        },
        {
          infinitive: 'buy',
          translation: 'a cumpăra',
          pastSimple: 'bought',
          pastParticipate: 'bought',
        },
        {
          infinitive: 'can',
          translation: 'a putea',
          pastSimple: 'could',
          pastParticipate: 'been able',
        },
        {
          infinitive: 'catch',
          translation: 'a prinde/a captura',
          pastSimple: 'caught',
          pastParticipate: 'caught',
        },
        {
          infinitive: 'choose',
          translation: 'a alege',
          pastSimple: 'chose',
          pastParticipate: 'chosen',
        },
        {
          infinitive: 'come',
          translation: 'a veni',
          pastSimple: 'came',
          pastParticipate: 'came',
        },
        {
          infinitive: 'cost',
          translation: 'a costa',
          pastSimple: 'cost',
          pastParticipate: 'cost',
        },
        {
          infinitive: 'cut',
          translation: 'a tăia',
          pastSimple: 'cut',
          pastParticipate: 'cut',
        },
        {
          infinitive: 'dig',
          translation: 'a săpa',
          pastSimple: 'dug',
          pastParticipate: 'dug',
        },
        {
          infinitive: 'do',
          translation: 'a face',
          pastSimple: 'did',
          pastParticipate: 'done',
        },
        {
          infinitive: 'draw',
          translation: 'a desena',
          pastSimple: 'drew',
          pastParticipate: 'drawn',
        },
        {
          infinitive: 'dream',
          translation: 'dreamed/dreamt',
          pastSimple: 'a visa',
          pastParticipate: 'dreamed/dreamt',
        },
        {
          infinitive: 'drink',
          translation: 'a bea',
          pastSimple: 'drank',
          pastParticipate: 'drunk',
        },
        {
          infinitive: 'drive',
          translation: 'a conduce',
          pastSimple: 'drove',
          pastParticipate: 'driven',
        },
        {
          infinitive: 'eat',
          translation: 'a mânca',
          pastSimple: 'ate',
          pastParticipate: 'eaten',
        },
        {
          infinitive: 'fall',
          translation: 'a cădea',
          pastSimple: 'fell',
          pastParticipate: 'fallen',
        },
        {
          infinitive: 'feed',
          translation: 'a hrăni',
          pastSimple: 'fed',
          pastParticipate: 'fed',
        },
        {
          infinitive: 'feel',
          translation: 'a simți',
          pastSimple: 'felt',
          pastParticipate: 'felt',
        },
        {
          infinitive: 'fight',
          translation: 'a lupta',
          pastSimple: 'fought',
          pastParticipate: 'fought',
        },
        {
          infinitive: 'find',
          translation: 'a găsi',
          pastSimple: 'found',
          pastParticipate: 'found',
        },
        {
          infinitive: 'fly',
          translation: 'a zbura',
          pastSimple: 'flew',
          pastParticipate: 'flown',
        },
        {
          infinitive: 'forget',
          translation: 'a uita',
          pastSimple: 'forgot',
          pastParticipate: 'forgotten',
        },
        {
          infinitive: 'forgive',
          translation: 'a ierta',
          pastSimple: 'forgave',
          pastParticipate: 'forgiven',
        },
        {
          infinitive: 'freeze',
          translation: 'a îngheța',
          pastSimple: 'froze',
          pastParticipate: 'frozen',
        },
        {
          infinitive: 'get',
          translation: 'a obține',
          pastSimple: 'got',
          pastParticipate: 'got',
        },
        {
          infinitive: 'give',
          translation: 'a da/a oferi',
          pastSimple: 'gave',
          pastParticipate: 'given',
        },
        {
          infinitive: 'go',
          translation: 'a merge',
          pastSimple: 'went',
          pastParticipate: 'gone/been',
        },
        {
          infinitive: 'grow',
          translation: 'a crește',
          pastSimple: 'grew',
          pastParticipate: 'grown',
        },
        {
          infinitive: 'hang',
          translation: 'a atârna',
          pastSimple: 'hanged/hung',
          pastParticipate: 'hanged/hung',
        },
        {
          infinitive: 'have',
          translation: 'a avea',
          pastSimple: 'had',
          pastParticipate: 'had',
        },
        {
          infinitive: 'hear',
          translation: 'a auzi',
          pastSimple: 'heard',
          pastParticipate: 'heard',
        },
        {
          infinitive: 'hide',
          translation: 'a ascunde',
          pastSimple: 'hid',
          pastParticipate: 'hidden',
        },
        {
          infinitive: 'hit',
          translation: 'a lovi',
          pastSimple: 'hit',
          pastParticipate: 'hit',
        },
        {
          infinitive: 'hold',
          translation: 'a ține',
          pastSimple: 'held',
          pastParticipate: 'held',
        },
        {
          infinitive: 'hurt',
          translation: 'a răni/a durea',
          pastSimple: 'hurt',
          pastParticipate: 'hurt',
        },
        {
          infinitive: 'keep',
          translation: 'a păstra',
          pastSimple: 'kept',
          pastParticipate: 'kept',
        },
        {
          infinitive: 'kneel',
          translation: 'a îngenunchia',
          pastSimple: 'knelt',
          pastParticipate: 'knelt',
        },
        {
          infinitive: 'know',
          translation: 'a ști',
          pastSimple: 'knew',
          pastParticipate: 'known',
        },
        {
          infinitive: 'lay',
          translation: 'a așeza',
          pastSimple: 'laid',
          pastParticipate: 'laid',
        },
        {
          infinitive: 'lead',
          translation: 'a conduce',
          pastSimple: 'led',
          pastParticipate: 'led',
        },
        {
          infinitive: 'learn',
          translation: 'a învăța',
          pastSimple: 'learned/learnt',
          pastParticipate: 'learned/learnt',
        },
        {
          infinitive: 'leave',
          translation: 'a pleca/a părăsi',
          pastSimple: 'left',
          pastParticipate: 'left',
        },
        {
          infinitive: 'lend',
          translation: 'a împrumuta',
          pastSimple: 'lent',
          pastParticipate: 'lent',
        },
        {
          infinitive: 'let',
          translation: 'a lăsa',
          pastSimple: 'let',
          pastParticipate: 'let',
        },
        {
          infinitive: 'lie',
          translation: 'a minți',
          pastSimple: 'lay',
          pastParticipate: 'lain',
        },
        {
          infinitive: 'light',
          translation: 'a lumina',
          pastSimple: 'lit',
          pastParticipate: 'lit',
        },
        {
          infinitive: 'lose',
          translation: 'a pierde',
          pastSimple: 'lost',
          pastParticipate: 'lost',
        },
        {
          infinitive: 'make',
          translation: 'a face',
          pastSimple: 'made',
          pastParticipate: 'made',
        },
        {
          infinitive: 'mean',
          translation: 'a însemna',
          pastSimple: 'meant',
          pastParticipate: 'meant',
        },
        {
          infinitive: 'meet',
          translation: 'a înlâlni',
          pastSimple: 'met',
          pastParticipate: 'met',
        },
        {
          infinitive: 'must',
          translation: 'a trebui',
          pastSimple: 'had to',
          pastParticipate: 'had to',
        },
        {
          infinitive: 'pay',
          translation: 'a plăti',
          pastSimple: 'paid',
          pastParticipate: 'paid',
        },
        {
          infinitive: 'put',
          translation: 'a pune',
          pastSimple: 'put',
          pastParticipate: 'put',
        },
        {
          infinitive: 'read',
          translation: 'a citi',
          pastSimple: 'read',
          pastParticipate: 'read',
        },
        {
          infinitive: 'ride',
          translation: 'a călări',
          pastSimple: 'rode',
          pastParticipate: 'ridden',
        },
        {
          infinitive: 'ring',
          translation: 'a suna',
          pastSimple: 'rang',
          pastParticipate: 'rung',
        },
        {
          infinitive: 'rise',
          translation: 'a crește/a ridica',
          pastSimple: 'rose',
          pastParticipate: 'risen',
        },
        {
          infinitive: 'run',
          translation: 'a alerga',
          pastSimple: 'ran',
          pastParticipate: 'run',
        },
        {
          infinitive: 'say',
          translation: 'a zice/a spune',
          pastSimple: 'said',
          pastParticipate: 'said',
        },
        {
          infinitive: 'see',
          translation: 'a vedea',
          pastSimple: 'saw',
          pastParticipate: 'seen',
        },
        {
          infinitive: 'sell',
          translation: 'a vinde',
          pastSimple: 'sold',
          pastParticipate: 'sold',
        },
        {
          infinitive: 'send',
          translation: 'a trimite/a expedia',
          pastSimple: 'sent',
          pastParticipate: 'sent',
        },
        {
          infinitive: 'set',
          translation: 'a stabili',
          pastSimple: 'set',
          pastParticipate: 'set',
        },
        {
          infinitive: 'shake',
          translation: 'a scutura/a agita',
          pastSimple: 'shook',
          pastParticipate: 'shaken',
        },
        {
          infinitive: 'shine',
          translation: 'a străluci',
          pastSimple: 'shone',
          pastParticipate: 'shone',
        },
        {
          infinitive: 'shoot',
          translation: 'a împușca/a trage',
          pastSimple: 'shot',
          pastParticipate: 'shot',
        },
        {
          infinitive: 'show',
          translation: 'a arăta',
          pastSimple: 'showen',
          pastParticipate: 'shown',
        },
        {
          infinitive: 'shut',
          translation: 'a închide',
          pastSimple: 'shut',
          pastParticipate: 'shut',
        },
        {
          infinitive: 'sing',
          translation: 'a cânta',
          pastSimple: 'sang',
          pastParticipate: 'sung',
        },
        {
          infinitive: 'sink',
          translation: 'a scufunda',
          pastSimple: 'sank',
          pastParticipate: 'sunk',
        },
        {
          infinitive: 'sit',
          translation: 'a sta',
          pastSimple: 'sat',
          pastParticipate: 'sat',
        },
        {
          infinitive: 'sleep',
          translation: 'a dormi',
          pastSimple: 'slept',
          pastParticipate: 'slept',
        },
        {
          infinitive: 'slide',
          translation: 'a aluneca/a luneca',
          pastSimple: 'slid',
          pastParticipate: 'slid',
        },
        {
          infinitive: 'smell',
          translation: 'a mirosi',
          pastSimple: 'smelled/smelt',
          pastParticipate: 'smelled/smelt',
        },
        {
          infinitive: 'speak',
          translation: 'a vorbi',
          pastSimple: 'spoke',
          pastParticipate: 'spoken',
        },
        {
          infinitive: 'spend',
          translation: 'a cheltui',
          pastSimple: 'spent',
          pastParticipate: 'spent',
        },
        {
          infinitive: 'spill',
          translation: 'a vărsa/a împrăștia',
          pastSimple: 'spilled/spilt',
          pastParticipate: 'spilled/spilt',
        },
        {
          infinitive: 'spoil',
          translation: 'a strica/a alinta',
          pastSimple: 'spoiled/spoilt',
          pastParticipate: 'spoiled/spoilt',
        },
        {
          infinitive: 'stand',
          translation: 'a sta',
          pastSimple: 'stood',
          pastParticipate: 'stood',
        },
        {
          infinitive: 'steal',
          translation: 'a fura/a răpi',
          pastSimple: 'stole',
          pastParticipate: 'stolen',
        },
        {
          infinitive: 'stick',
          translation: 'a lipi',
          pastSimple: 'stuck',
          pastParticipate: 'stuck',
        },
        {
          infinitive: 'swim',
          translation: 'a înota',
          pastSimple: 'swam',
          pastParticipate: 'swam',
        },
        {
          infinitive: 'take',
          translation: 'a lua',
          pastSimple: 'took',
          pastParticipate: 'taken',
        },
        {
          infinitive: 'teach',
          translation: 'a învăța',
          pastSimple: 'thought',
          pastParticipate: 'thought',
        },
        {
          infinitive: 'tear',
          translation: 'a sfâșia/a rupe',
          pastSimple: 'tore',
          pastParticipate: 'torn',
        },
        {
          infinitive: 'tell',
          translation: 'a spune',
          pastSimple: 'told',
          pastParticipate: 'told',
        },
        {
          infinitive: 'think',
          translation: 'a gândi',
          pastSimple: 'thought',
          pastParticipate: 'thought',
        },
        {
          infinitive: 'throw',
          translation: 'a arunca',
          pastSimple: 'threw',
          pastParticipate: 'thrown',
        },
        {
          infinitive: 'understand',
          translation: 'a înțelege',
          pastSimple: 'understood',
          pastParticipate: 'understood',
        },
        {
          infinitive: 'wake',
          translation: 'a trezi',
          pastSimple: 'woke',
          pastParticipate: 'woken',
        },
        {
          infinitive: 'wear',
          translation: 'a purta',
          pastSimple: 'wore',
          pastParticipate: 'worn',
        },
        {
          infinitive: 'win',
          translation: 'a câștiga',
          pastSimple: 'won',
          pastParticipate: 'won',
        },
        {
          infinitive: 'write',
          translation: 'a scrie',
          pastSimple: 'wrote',
          pastParticipate: 'written',
        },
      ],
    }
  },
}
</script>
